### PR TITLE
Summary report

### PR DESCRIPTION
**Pull request by pkbullock**
Hi

- Added summary capability after rewrite
- Added critical exception capture so that total fails are captured in report
- Yet to do - increase logging points

Related to #113 

**WARNING** contains a build issue when merging dev into this branch before PR - @jansenbe  can you help with this I lack context of the url rewrite, page transformation information changes.

### CODE REVIEW

**Comment by jansenbe** [comment]
Again a great work @pkbullock , thanks a lot for helping out on making page transformation a great tool!

**Comment by pkbullock** [comment]
@jansenbe I have noticed that with the PublishingPageTransformator class and some of the changes could be undone when merging, e.g. URL rewrite move, updating my branch doesn't reflect the latest commits

**Comment by jansenbe** [comment]
@pkbullock : just tried to merge this but indeed for some reason it's not merging the changes, it's literally setting everything back several commits. Let me see if I can some how fix this

**Comment by pkbullock** [comment]
The only change I made to those classes, was to wrap the majority of the code in a try catch, to capture any total failure for reporting. This indented all the code and I think that’s where the clash came in

Also to mark specific log entries with significance for summary.

Get Outlook for iOS<https://aka.ms/o0ukef>

________________________________

**Comment by jansenbe** [comment]
No worries, I'll do a manual merge tomorrow or later today...think that's the easiest and safest for now.

**Comment by jansenbe** [comment]
@pkbullock : manually merged + did some tweaking

**Pull request closed without merging**
