### PR TITLE
Fix for SharePoint 2010 and support Web Part Pages, Wiki Pages

### PR DESCRIPTION
**Pull request by pkbullock**
Fixes issues with

- Content Editor not transforming
- Split of PublishingPage class to perform OnPremises analysis

Added:

- Some unit test improvements
- Support for 2010 Web Part Pages
- Support for 2010 Wiki Pages

Related to #204

### CODE REVIEW

**Comment by pkbullock** [comment]
I will be adding support for Web Part Page 2010 which isn't included thus far... will be careful with checkins for now... until this is merged.

**Comment by pkbullock** [comment]
There is an issue with Web Part Page Title Bar, so going to fix that next.

**Comment by jansenbe** [comment]
Thx again @pkbullock !

I've merged this one and did a few tweaks:

- changed call to GetSitePagesLibrary() in Load method of PageTransformator to only apply in 2010 case -> not sure what the specific reason for this method was. If the original code also works for 2010 then I'm in favor of just keep using that as it will avoid a too early call to ExecuteQuery
- changed some executequery to executequeryretry (to improve reliability in case of throttling)
- improved GetUrl to avoid unneeded executequery calls in non 2010 scenarios (for performance reasons)

**Comment by pkbullock** [comment]
@jansenbe welcome back!

All good stuff, thank you for your input, its always valuable to have that sanity check and reduce the chance this impacts other SP versions transformation.  

The GetSitePagesLibrary was used to work around gaps in CSOM where there isn't a GetList method. Same for GetUrl - Web.Url doesn't exist in CSOM. 

In the SharePoint 2010 piece, there are loads of gaps in CSOM properties and methods not being present, luckily the majority we use are there except in the above, and anything important we need is supplemented by Web Service calls where required.

**Pull request merged**
