### PR TITLE
Term mapping feature

### PR DESCRIPTION
**Pull request by pkbullock**
Related to #187 

Term store mapping includes
- Mapping term store default and manual modes
- Unit Tests + sample CSV (for my term store)
- Some testing including 2013, SPO Publishing Sites and limited Team Sites
- Testing included Single and Multiple terms

Not yet done:
- Testing in SP2010
- Exported my term sets as example

I'm submitting slightly early, probably some polishing to do, to ask for help testing this, as we both have different testing scenarios, should yield better coverage.

### CODE REVIEW

**Comment by pkbullock** [comment]
Just done some testing of wiki pages in SP 2010 appears not to work, it cannot cast the field to TaxonomyField.

**Comment by pkbullock** [comment]
For the moment, this PR doesn't support 2010 because there are no CSOM methods for taxonomy session class to read the term store, so currently writing the fall back code.

**Comment by jansenbe** [comment]
Wohoo!!! Awesome work @pkbullock !! I'll start the merge work today so that there's plenty of testing time before we ship the March release

**Comment by pkbullock** [comment]
Just going to add 2010 now.

**Comment by pkbullock** [comment]
Just listing out from a recent sweep on tests:

Known issues/bugs so far:

- Publishing page support for 2010 not yet implemented, but is for wiki/web part
- 2010 cannot get the term group (SSPID label) to add to the path mapping on source so will need to work around that
- Lines 516 in BasePageTransformator not defensive enough, needs a try catch, other wise whole transform pipeline has critical error (stop all transform) 
- Need to investigate "Invalid data has been used to update the list item. The field you are trying to update may be read only" in Wiki Page Transform with terms.

**Comment by pkbullock** [comment]
Ill wait until your merge now, pls review the code, few late nights involved so wondering if this is best way of implementing or might have gaps.

**Comment by jansenbe** [comment]
Overall code looks good, I think some perf optimizations are needed which I'll work on together with testing. Running my current test cases as a first basic test round and will then commit so that you create PR's for your additional changes + others that want to also test can do that.

**Comment by jansenbe** [comment]
Merged this one in two steps, hope I got everything from your last changes in as I had some merge conflicts

**Comment by pkbullock** [comment]
Ah sorry about this, my fault for submitting and then making changes, I was hoping to avoid this.

**Comment by jansenbe** [comment]
Np, I also should have refreshed my branch before merging it. The merge work wasn't hard, should all be good

**Pull request merged**
