### PR TITLE
Levelled the versions for Identity Model to 1.2.4 to enable unit testing and cross site option for transformation

### PR DESCRIPTION
**Pull request by pkbullock**
Minor fix for issue #54 to use a single version of the dependency

### CODE REVIEW

**Comment by pkbullock** [comment]
This is a minor fix to allow some of the unit tests to build

**Comment by pkbullock** [comment]
Hi 

I was working on the ability to specify a target site such as a communication site. The cross unit test shows an example of usage. This can eventually, provide the option to transform directly to modern site. If a target context is not specified, then the transformation will take place on the same site, as it has been doing currently.

This includes some renaming of the context variable to provider clearer identification in the code for which the context refers to. 

Paul

**Comment by jansenbe** [comment]
Nice work @pkbullock! Being able to create the page another site collection is a feature that will be required for handling publishing migration scenarios. I'll process this PR soon.

**Comment by jansenbe** [comment]
Hi @pkbullock,

Did merge this PR combined with some further changes required to support this (more in particular in the item level permissions handling). I've also added a check on the banner web part use as that makes no sense in my opinion on a page created in another site collection. Final other thing is that in case of different target site collection I always configure the page transformation engine to create the page with the same name as the source page. 

Following changes are still needed:
- Implement page metadata copy (requires the optional creation of page fields to store the metadata)
- Verify individual web parts: web parts do tend to have references to the source site and therefore some of them will not work

Labeled this as experimental in the release notes for now.

**Comment by pkbullock** [comment]
@jansenbe liking the code changes and the list of features. I will have a look for my next PRs.

**Pull request merged**
