### PR TITLE
Added additional check while updating PageModification fields

### PR DESCRIPTION
**Pull request by gautamdsheth**
This PR adds additional check to determine whether the transformation is being done by user having Owner/Admin permissions or not. 

If we don't have Owner permissions, then the Created/Modified/Author fields are not set. It will set it to the current user and time. Only when we have Owner/Admin permissions does this work.

Additionally, I noticed that modified by field is not set, any idea why ? Other fields like created, author and modified are set correctly, only editor is not set.

### CODE REVIEW

**Comment by jansenbe** [comment]
Noticed the Editor setting as well...that used to work when I developed the feature but over the last week it stopped working. Not sure why yet.

About the owner permission check...based on your description there's no error, it just never works. Right?

**Comment by gautamdsheth** [comment]
Oh ok. Yes about the owner permission check, discovered it today when the customer forgot to give me owner permission. The page was transformed correctly and the metadata was copied over as well. There was no error, just that created/author/modified fields didn't get copied over. After i got owner permissions later on, it those fields got copied over correctly as well. But would be great if you have some time and can double check ?

**Comment by jansenbe** [comment]
Hi @gautamdsheth,
 
Did some research/testing with setting the Editor property...this works if we're not publishing the create page. I've so far found no way to keep Editor set to the "old" value while in the same time keep the page published...

**Comment by jansenbe** [comment]
Hey @gautamdsheth ,

Since setting the editor/author/created/modified does not fail when one has just edit permissions I don't think it's good to incur the cost of checking this. I've updated the docs to spell this out: https://docs.microsoft.com/en-us/sharepoint/dev/transform/modernize-userinterface-site-pages-security.

Hence I think it's best to close this PR and not merge it.

**Pull request closed without merging**
