### PR TITLE
SharePoint 2010 Preview Support

### PR DESCRIPTION
**Pull request by pkbullock**
Ok this is a bit of a PR but here it is for supporting 2010 so far:

- Added multiple workarounds and alternative calls  for unsupported CSOM calls with fallbacks to Web Services
- Move SP version detection in the class hierarchy
- Refactored calls to Get Publishing Pages library name
- Updated Asset transfer to use alternative calls for older environments
- Logging and tests
- Added Assert Fail if unit test observer contains critical error

Known issue:
 - URL transform screws up rendering, will look at and fix if you are on holiday - Ref #205 

In the meantime, will work on tests, tests, tests across the versions.
Have taken (today) latest code and merged in, so should be painless merge.... 
Related to issue #183

### CODE REVIEW

**Comment by jansenbe** [comment]
Awesome contribution @pkbullock, thanks a ton for doing this work. I'll try to get it merged in the coming week, should have some free time :-)

**Comment by jansenbe** [comment]
Hi @pkbullock , thanks again for the ton of work you did to enable 2010 support. I've merged this PR and all looked good but found an issue with web part retrieval while testing. I've changed the code to fix this while keeping your 2010 flow working, at least that's what I think as I currently don't have a 2010 farm available for testing. So please cross check things still work for you with 2010.

**Comment by pkbullock** [comment]
@jansenbe thanks for checking this, unfortunately this failed in 2010 because ExportMode and ZoneId are not instantiated, these are not available from CSOM on lines 294, 369 and 331 of the PublishingPage class. I added to check this:

```c#
WebPartExportMode exportMode = foundWebPart.WebPartDefinition.WebPart.IsObjectPropertyInstantiated("ExportMode") ?foundWebPart.WebPartDefinition.WebPart.ExportMode : default(WebPartExportMode); 
```
and
```c#

string zoneId = foundWebPart.WebPartDefinition.IsObjectPropertyInstantiated("ZoneId") ? foundWebPart.WebPartDefinition.ZoneId : string.Empty;

```
I'm wondering if I should have coded this differently either dedicated class or extension methods to reduce the impact between SharePoint versions. Not all SharePoint CSOM properties are available in 2010 I have added extension methods to work around these.

I ran tests for this on SPO transform, which means you have a test case/scenario that I don't or just missed things... what broke?

**Comment by jansenbe** [comment]
problem was that exportmode, zoneid and web part xml are not filled for non SP2010 flow, the web parts are found but these properties are needed for the correct detection of the web part type. Using .Value for the webpartxml loading didn't work as all requests are queued up and handled by a single server request. Maybe it's easier to just add more if then constructs that provide different behavior for 2010 versus trying to integrate it?

**Comment by jansenbe** [comment]
In my test case I have 2 content editor web parts and an XSLTListView web part in a single zone, with your code merged the content editor web parts were dropped.

**Comment by pkbullock** [comment]
@jansenbe thanks for the pointers, ill check the code again with your test cases and submit a new PR when both flows work.

**Pull request merged**
